#!/usr/bin/env php

<?php

use App\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;

set_time_limit(0);

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

if (!class_exists(Application::class)) {
    throw new \RuntimeException('You need to add "symfony/framework-bundle" as a Composer dependency.');
}

$env = 'prod';
$debug = false;
$kernel = new Kernel($env, $debug);
$app = new Application($kernel);
$app->setName('gBere cli');
$app->setVersion('0.3.0');
$app->run($input);
