#!/usr/bin/env php

<?php

use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Application('gBere cli', '0.2.0');
$app->addCommands([
    new App\Command\SayHelloCommand(),
]);
$app->run();
