#!/usr/bin/env php

<?php

use App\KernelProd;
use Symfony\Bundle\FrameworkBundle\Console\Application;

set_time_limit(0);

const APP_NAME      = 'gBere cli';
const APP_VERSION   = '0.3.11';

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

if (!class_exists(Application::class)) {
    throw new \RuntimeException('You need to add "symfony/framework-bundle" as a Composer dependency.');
}

$kernel = new KernelProd('prod', false);
$app = new Application($kernel);
$app->setName(APP_NAME);
$app->setVersion(APP_VERSION);
$app->run($input);
