#!/usr/bin/env php
<?php

use App\Kernel;
use App\GbApplication;

set_time_limit(0);

const APP_NAME      = 'gBere cli';
const APP_VERSION   = '0.6.1';

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$kernel = new Kernel('prod', false);
$app = new GbApplication($kernel);
$app->setName(APP_NAME);
$app->setVersion(APP_VERSION);
$app->run();
