#!/usr/bin/env php
<?php

use App\KernelProd;
use App\ApplicationProd;

set_time_limit(0);

const APP_NAME      = 'gBere cli';
const APP_VERSION   = '0.4.3';

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$kernel = new KernelProd('prod', false);
$app = new ApplicationProd($kernel);
$app->setName(APP_NAME);
$app->setVersion(APP_VERSION);
$app->run();
